### ISSUE TITLE
feat: landing page (design)

### ISSUE THREAD

**Issue by niloysikdar** [niloysikdar/Kahani#1]
Need to design the landing page for the app.

### Required skills:
HTML, good CSS (preferably Sass) skills, basics of React

### Example wireframe:
You don't need to follow the same design, feel free to create your own

![Untitled-2022-02-23-1454](https://user-images.githubusercontent.com/58071992/155292688-9c5339f6-279c-48ee-8f46-dd2f9adfab65.png)

### Important
You need to come up with a good color scheme and UI design, you can use Figma

**Comment by Ankit62042** [comment]
I want to work on this issue

**Comment by niloysikdar** [comment]
Sure @Ankit62042 , go ahead

**Comment by Ankit62042** [comment]
![Kahani website](https://user-images.githubusercontent.com/71378462/155870451-454ea402-a05d-4336-97ef-62acbab1caf7.png)

landing page UI Design

**Comment by Ankit62042** [comment]
![Kahani ka fasana](https://user-images.githubusercontent.com/71378462/155870536-2caac4cc-f5d0-4059-83ea-0ca34d2f46b1.png)

Updated UI Page

**Comment by niloysikdar** [comment]
LGTM @Ankit62042 
Update [this file](https://github.com/niloysikdar/Kahani/blob/main/DESIGN.md) with your design and submit a pull request
