### ISSUE TITLE
feat: content page (design)

### ISSUE THREAD

**Issue by niloysikdar** [niloysikdar/Kahani#3]
Need to design the content page where we can render the story or poem for the app.

### Required skills:
HTML, good CSS (preferably Sass) skills, basics of React

### Example wireframe:
You don't need to follow the same design, feel free to create your own

![Untitled-2022-02-23-1510](https://user-images.githubusercontent.com/58071992/155296931-71ff5561-cf9e-48f2-9f41-ec1ada12bddc.png)

### Important
You need to come up with a good color scheme and UI design, you can use Figma

**Comment by Ankit62042** [comment]
I want to work on this issue

**Comment by niloysikdar** [comment]
Assigned you @Ankit62042

**Comment by Ankit62042** [comment]
![Content page](https://user-images.githubusercontent.com/71378462/155871656-585bcbc3-e6b3-423e-ae3e-a7c15bc9082c.png)

Landing Page UI Design Using Figma

**Comment by niloysikdar** [comment]
LGTM @Ankit62042
Update [this file](https://github.com/niloysikdar/Kahani/blob/main/DESIGN.md) with your design and submit a pull request
